name: CandySpawners
main: com.candyspawners.CandySpawners
version: 1.3
api-version: 1.19
author: Berk AYDIN
depend: [HolographicDisplays]

commands:
  candyspawners:
    description: CandySpawners ana komutu.
    usage: /candyspawners <give|info|list|gui>
  nbtoku:
    description: Elde tutulan sandığın NBT verisini gösterir.
    usage: /nbtoku
